/**
 * Kernel · world geometry
 * ---------------------------------------------------------------------------
 * The block grid behind the world map. It is a static asset generated by
 * `scripts/build-world-map.mjs` and imported on the server, so the map renders
 * in the initial HTML — no client fetch, no layout shift, and the whole thing
 * works without JavaScript.
 */

import raw from '@/lib/data/world-map.json'

export type WorldCell = number[]
export type WorldCountry = { name: string; tiny: boolean; cells: WorldCell[] }
export type WorldGeometry = {
  cell: number
  cols: number
  rows: number
  width: number
  height: number
  countries: Record<string, WorldCountry>
}

/* JSON imports widen tuples to arrays, so go through unknown. */
const world = raw as unknown as WorldGeometry

export function getWorld(): WorldGeometry {
  return world
}

/** One path per country: a run of square blocks with a hairline gap between them. */
export function blocksToPath(cells: WorldCell[], cell: number, inset: number, dy = 0): string {
  const size = cell - inset
  let d = ''
  for (const [col, row] of cells) {
    const x = col * cell + inset / 2
    const y = row * cell + inset / 2 + dy
    d += `M${x} ${y}h${size}v${size}h${-size}z`
  }
  return d
}
